"""add risk fields

Revision ID: d5db4a813fc7
Revises: 04cdf04aacd3
Create Date: 2026-09-14 16:37:34.393124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5db4a813fc7'
down_revision: Union[str, Sequence[str], None] = '04cdf04aacd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_results', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('verification_results', sa.Column('risk_reasons', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_results', 'risk_reasons')
    op.drop_column('verification_results', 'risk_level')
    # ### end Alembic commands ###
